env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - google
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
plugins:
  - "@typescript-eslint"
rules: {
  "complexity": ["error", 20],
  "require-jsdoc": ["warn"],
  "no-unused-vars": "off",
  "@typescript-eslint/no-unused-vars": ["error", { "vars": "all", "argsIgnorePattern": "^_$" }]
}
