# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy npm

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ls -R
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
    - run: yarn
    - run: yarn lint:ci
    - run: yarn test:cov
    - run: yarn build
    - run: yarn doc
    - run: mv ./dist/docs ./docs
    - run: tar cvzf parsegraph-docs.tgz ./docs
    - run: mkdir -p ~/.ssh
    - run: echo -n "$SSH_TOKEN" | base64 -d >$HOME/.ssh/id_rsa
    - run: file $HOME/.ssh/id_rsa
    - run: chmod 0400 $HOME/.ssh/id_rsa
    - run: echo "3d6b11a37bb1bd4f418de3686c851a58d5673ad0 *$HOME/.ssh/id_rsa" | sha1sum -c
      env:
          SSH_TOKEN: ${{ secrets.PARSEGRAPH_SSH_TOKEN }}
    - run: echo -n "$SSH_KNOWN_HOST" | base64 -d >>$HOME/.ssh/known_hosts
      env:
          SSH_KNOWN_HOST: ${{ secrets.PARSEGRAPH_SSH_KNOWN_HOST }}
    - run: ssh "$SSH_HOST" 'echo "Hello, world!"'
      env:
          SSH_HOST: ${{ secrets.PARSEGRAPH_SSH_HOST }}
    - run: scp parsegraph-docs.tgz "$SSH_HOST:"
      env:
          SSH_HOST: ${{ secrets.PARSEGRAPH_SSH_HOST }}
    - run: mv ./dist/coverage ./coverage
    - run: yarn tar
    - run: yarn deploy
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    - run: tar cvzf parsegraph.tgz parsegraph/
    - uses: actions/upload-artifact@v2
      with:
        name: parsegraph-${{ github.run_number }}
        path: parsegraph.tgz
    - uses: actions/upload-artifact@v2
      with:
        name: parsegraph-docs-${{ github.run_number }}
        path: parsegraph-docs.tgz
    - run: tar cvzf parsegraph-coverage.tgz ./coverage
    - uses: actions/upload-artifact@v2
      with:
        name: parsegraph-coverage-${{ github.run_number }}
        path: parsegraph-coverage.tgz
