# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy npm

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ls -R
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
    - run: yarn
    - run: yarn lint
    - run: yarn test:cov
    - run: yarn build
    - run: yarn doc
    - run: mv ./dist/docs ./docs
    - run: yarn tar
    - run: yarn deploy
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    - run: tar cvzf parsegraph.tgz parsegraph/
    - uses: actions/upload-artifact@v2
      with:
        name: parsegraph-${{ github.run_number }}
        path: parsegraph.tgz
    - run: tar cvzf parsegraph-doc.tgz parsegraph/dist/docs
    - uses: actions/upload-artifact@v2
      with:
        name: parsegraph-docs-${{ github.run_number }}
        path: parsegraph-docs.tgz
