# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v2
    - run: ls -R
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - run: make install-deps
    - run: make build
    - run: make tar
    - run: ./publish.sh
      if: ${{ matrix.node-version == '18.x' }}
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    - run: git push --tags
    - uses: actions/upload-artifact@v2
      with:
        name: parsegraph-layout-dev-${{ github.run_number }}-${{ matrix.node-version }}
        path: parsegraph-layout-dev.tgz
