# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - run: ls -R
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: NODE_ENV=production npm ci --omit=dev
    - run: NODE_ENV=production make clean build-prod
    - run: NODE_ENV=production make tar-prod
    - uses: actions/upload-artifact@v2
      with:
        name: parsegraph-layout-prod-${{ github.run_number }}
        path: parsegraph-layout-prod.tgz
